### ISSUE TITLE
need help with sql

### ISSUE THREAD

**Issue by X-Anonymous-Y** [ccasad/ng-login#1]
Hello Chris,

I'm learning Angular and PHP
I wanted to test the app.

The app also works very well so far.

The question I am now just ask is ...
Where can I find the .sql file for the tables?

Would be very happy about help.

regards
Kamil

**Comment by xpandgithub** [comment]
Kamil,

I just added a database.sql file to the repository. Hopefully that matches what you're looking for. This repo is pretty old so I had to dig up the old database, but I'm pretty sure that's it.

--Chris

**Comment by ccasad** [comment]
Kamil, I just added a database.sql file to the repository. Hopefully that matches what you're looking for. This repo is pretty old so I had to dig up the old database.

--Chris
